### ISSUE TITLE
Double child ids on structs

### ISSUE THREAD

**Issue by steveklabnik** [nrc/rls-analysis#105]
Given a `lib.rs` that looks like this:

```
/// struct docs
pub struct Struct {
    /// field docs
    pub field: i32,
}
```

I have some code that looks like this:

```rust
        let child_ids = host.for_each_child_def(id, |id, _def| {
            id
        })?;

        let def = host.get_def(id).unwrap();
        println!("Generating docs for {}", def.qualname);
        println!("kind: {:?}", def.kind);
        println!("child_ids: {:?}", child_ids);
```

This will print

```text
Generating docs for example::Struct
kind: Struct
child_ids: [Id(57982058505), Id(57982058505)]
```

Why am I getting two child ids? Putting a `println` inside of `for_each_child_def` also prints twice, with the same id each time.

**Comment by steveklabnik** [comment]
Seeing this with enums as well, double on the variants

**Comment by steveklabnik** [comment]
@nrc ping; this bug isn't TOO severe, as we only generate one thing anyway, but it does mean we do work twice

**Comment by nrc** [comment]
Note for self for tomorrow, I think this is a bug in save-analysis, not the compiler. And I think because the struct has children and the children have a parent, they are two parent-child relations, and we're adding them both.

**Comment by nrc** [comment]
This is in 0.7.2
