### ISSUE TITLE
link prefix components in paths

### ISSUE THREAD

**Issue by nrc** [nrc/rls-analysis#109]
e.g., foo and bar in foo::bar::baz; currently we only have info for baz. This will require a name resolution fix in the compiler.

**Comment by nrc** [comment]
cc @Xanewok who was interested in implementing this and @jseyfried who probably knows how to do it.

**Comment by norru** [comment]
Is this project abandoned?

**Comment by nrc** [comment]
> Is this project abandoned?

No, it is used in the RLS

**Comment by pravic** [comment]
If it works, it will be a huge step.

**Comment by norru** [comment]
Uhm, could this be related? https://github.com/rust-lang/rust/issues/55480

**Comment by nrc** [comment]
> Uhm, could this be related? rust-lang/rust#55480

doesn't look like it, but thanks for the heads up

**Comment by pravic** [comment]
From https://github.com/rust-lang/rust/pull/55521

> This fixes the RLS tests, which are currently blocking distribution of the RLS. 

So, we can't try the new resolution yet, correct?

**Comment by nrc** [comment]
> So, we can't try the new resolution yet, correct?

Correct, we're waiting for 55521 to land and then a new nightly to come out. Hopefully tomorrow, maybe the next day.
