### ISSUE TITLE
No def roots?

### ISSUE THREAD

**Issue by steveklabnik** [nrc/rls-analysis#115]
When updating `rustdoc` to use the new rls-analysis and rls-data:

```
roots: []
```

That is, calling `let roots = host.def_roots()?;` is now yielding `Ok(Vec::new())` for some reason.

Any ideas? Is the way we're supposed to generate the analysis data changed?

**Comment by Xanewok** [comment]
rustc will emit compatible data with rls-data 0.12 starting from https://github.com/rust-lang/rust/commit/2379faa933923a97158a4939b9fc82dcbd45430f (current version https://github.com/rust-lang/rust/commit/2be4cc040211a85b17f21e813ff62351ae4de642 is behind a few commits) so thankfully it should work with rls-data 0.12 when 2017-11-02 rustc is published.

**Comment by steveklabnik** [comment]
Ah, figures something like that would be the cause. Thank you for the quick response!
