### ISSUE TITLE
Tons of errors about unexpected definition kinds during first analysis

### ISSUE THREAD

**Issue by sfackler** [nrc/rls-analysis#117]
I'm using rls master (`rls-preview 0.123.0-nightly (e0035b0 2017-11-07)`), and seeing a couple thousand ERROR-level messages when rls first boots up:

https://gist.github.com/sfackler/a05c0d6537259805ccd1147e8ab6e273

This is on a decently large repo with rls in workspace mode.

**Comment by DSpeckhals** [comment]
I am seeing the same thing with a similar build with any repo. For example, running the RLS on the `rls-analysis` repo logs the same messages.

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang/rust/pull/45848
