### ISSUE TITLE
Rust 2018 edition use statement with crate keyword not recognized

### ISSUE THREAD

**Issue by doxxx** [nrc/rls-analysis#144]
I'm using the Rust 2018 edition `use` statements with the `crate` keyword to reference modules in the local crate but rust_analysis doesn't recognize them:

```
error: expected identifier, found keyword `crate`
 --> bogofile:1:5
  |
1 | use crate::point::Point;
  |     ^^^^^
```

As a result, I get very little completion support in VSCode.

I have the following in my `cargo.toml`:

```
cargo-features = ["edition"]

[package]
edition = "2018"
```

I'm using rustc 1.28.0-nightly (e3bf634e0 2018-06-28).

**Comment by nrc** [comment]
Thanks for reporting this! It looks like a Racer bug, so I've moved it to https://github.com/racer-rust/racer/issues/880
