### ISSUE TITLE
`mod foo;` should be a goto def to `foo.rs`

### ISSUE THREAD

**Issue by nrc** [nrc/rls-analysis#23]
This is a bit of an odd case because we want to treat `mod foo;` differently to `mod foo { ... }` although the compiler mostly treats them as identical. It is also odd because `mod foo;` is the def for `foo` and is the only place that `foo` is named, however, from a practical point of view, IDE uses will want to easily jump from this declaration to the actual module definition. I'm not sure how this should appear in a 'find all refs' context - should we show `mod foo;` as the def or should the file be the def? And in the latter what should we use as the span? The first line of the file? The whole file?

**Comment by Nashenas88** [comment]
For 'find all refs', does it not allow you to differentiate between declaration and definition? As for what to show (for the purposes of selection), I would display the file name only for the definition and show the line normally for the declaration. If the users then jumps to the definition, either place the cursor at the first byte or highlight the first line. I don't see any usage to highlighting the entire file.

**Comment by nrc** [comment]
> For 'find all refs', does it not allow you to differentiate between declaration and definition?

We could make that distinction here, I don't think that the LS protocol makes that distinction. It doesn't really even distinguish between defs and refs, except you're meant to either return them or not. Rustw does distinguish refs from defs and could allow multiple defs, doesn't have the concept of a decl, though we could change that.

> I would display the file name only for the definition

This could work. It might look odd if the client is expecting a code snippet. We'd have to experiment.

**Comment by Nashenas88** [comment]
To clarify my above comment: I would want to see both when running 'find all refs'. I would want each for different use cases. I might want to see what else is in the module that the target module is declared in, or I would want to see what's in the targeted module.

**Comment by Nashenas88** [comment]
Sorry about the above. I submitted the comment right as my phone was buzzing that you responded.

**Comment by nrc** [comment]
fixed by https://github.com/rust-lang/rust/pull/37989
