### ISSUE TITLE
static method not linked

### ISSUE THREAD

**Issue by nrc** [nrc/rls-analysis#39]
`Aabb::new(Point::new(0.0, 0.0, 0.0), Point::new(0.0, 0.0, 0.0))` from objects,rs:253 in my ray tracer. The `new ` function for `Point` is linked, but for `Aabb` is not. I have no idea why. `Aabb` is linked elsewhere and it is in the same crate (which is the same crate as `Point`).

**Comment by nrc** [comment]
So I investigated this a bit - the problem is that `new` is generated by `derive(new)` and is not linked because of generated code weirdness. I think there is not an easy fix. We basically need to redo how we handle generated code, basically.

**Comment by jonathandturner** [comment]
@nrc - shouldn't we leave this open just not shoot to have it fixed by the beta?

**Comment by nrc** [comment]
I opened #51 for the more general issue of dealing with generated code. Static methods that are not generated are linked properly, so there is nothing more to do here.
