### ISSUE TITLE
How to distribute save-analysis for std libs

### ISSUE THREAD

**Issue by nrc** [nrc/rls-analysis#7]
Can we download with Rustdoc? Distribute with Rust downloads? Will need some infra work in either case.

Constraint is that we need to build them with exactly the same version of Rust used by the RLS user (not the version the RLS is built with).

**Comment by Nonius** [comment]
Would it be a lot of work if rustup would have a component for this? Like it has for the rust-src?

**Comment by nrc** [comment]
We are currently distributing these on r-l.o, next step is rustup integration.

**Comment by Nonius** [comment]
What is r-l.o?

**Comment by jrmuizel** [comment]
rust-lang.org

**Comment by nrc** [comment]
THis works with rustup now.
