### ISSUE TITLE
analysis::Def is private

### ISSUE THREAD

**Issue by euclio** [nrc/rls-analysis#81]
`AnalysisHost::get_def` returns `AResult<Def>` where `Def` is a private type. This type should be public since it's part of the public API.

**Comment by steveklabnik** [comment]
Was just about to file this!

**Comment by steveklabnik** [comment]
It looks like https://github.com/nrc/rls-analysis/commit/93cae44f643870dfdda8c82ce538959178609f21#diff-7c7d36a3ea1b5007423a60631c032f9bR11 is the cause, this should have been `pub`.
