### ISSUE TITLE
Macros and unions missing from analysis

### ISSUE THREAD

**Issue by projektir** [nrc/rls-analysis#97]
Relevant to [#121](https://github.com/steveklabnik/rustdoc/pull/177).

Similar story to impls, they seem to be part of the analysis, but not returned when calling `for_each_child_def`.

**Comment by steveklabnik** [comment]
@nrc ping; this one is a pretty big hole in rustdoc at the moment

**Comment by nrc** [comment]
macros are tracked in #50 (that's kind of a big job), I'm adding union support.

**Comment by nrc** [comment]
Unions: https://github.com/rust-lang/rust/pull/45647

**Comment by nrc** [comment]
Unions support has landed in the compiler, macros tracked elsewhere
