### ISSUE TITLE
EnumVariants not captured

### ISSUE THREAD

**Issue by projektir** [nrc/rls-analysis#98]
For [#121](https://github.com/steveklabnik/rustdoc/pull/177).

Enums are returned, but their variants are not.

**Comment by steveklabnik** [comment]
Update: 

```text
processing: example::SampleEnum::EnumVariant
kind: Tuple
```

That is, they're returned, but...

**Comment by steveklabnik** [comment]
@nrc ping; this one is kind of a blocker; not a *hard* one as we can always display the incorrect type for now, but it is weird and comes up a lot

**Comment by nrc** [comment]
This change, recently changed enums variants from `Tuple` kind to `TupleVariant` kind. I'll test if this fixes the issue...

**Comment by nrc** [comment]
OK, there is even a test for this. Note, that a struct variant will have kind `StructVariant`.

So this is fixed with version 0.7.1. Please re-open/comment if there are still issues.
