### ISSUE TITLE
Multiline docs not saved

### ISSUE THREAD

**Issue by projektir** [nrc/rls-analysis#99]
For [#121](https://github.com/steveklabnik/rustdoc/pull/177).

The `docs` attribute of a `Def` only seems to contain the first line of documentation. Maybe this is intended, but I'm not sure in that case where the rest of the docs are. So, for example:

```
/// This is an integer.
///
/// More docs.
let x: i32;
```

Only `This is an integer.` will be present in the `docs` field. Sometimes it gets a trailing `\n`, too, or a space in front.

**Comment by nrc** [comment]
It looks like this was just bad configuration?
